name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Compile project
        run: |
          echo "Compiling project..."
          find . -name "*.py" -exec sh -c 'echo "Compiling $1" && python -m py_compile "$1"' _ {} \;

  tests:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          pip install pytest pytest-cov
      
      - name: Run tests with coverage
        run: |
          pytest --cov=./ --cov-report=html
      
      - name: Upload test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/

  pep_verification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install flake8
        run: |
          pip install flake8
      
      - name: Run PEP8 verification
        run: |
          flake8 .
